### ISSUE TITLE
1.2.3版本，新装会报错，找不到文件夹.xtoolkit

### ISSUE THREAD

**Issue by momokoudai** [apache/incubator-weex-cli#236]
windows 10 x64
全新安装 weex-toolkit@1.2.3
运行任意weex命令会先提示统计，选择npm
然后报错。
原因是没有判断.xtoolkit这个目录是否存在。不存在的话需要创建。
错误如下：
`May weex-toolkit anonymously report usage statistics to improve the tool over time? Yes
? Which npm registry you perfer to use? npm
14:39:29 : Set telemetry => true
14:39:29 : Set registry => http://registry.npmjs.org
(node:10672) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\mypc\.xtoolkit\config.json'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at Object.exports.save (C:\Users\mypc\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\lib\util\config.js:44:6)
    at inquirer.prompt.then.answers (C:\Users\mypc\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\lib\util\ask.js:24:12)
    at <anonymous>
(node:10672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js
process with a non-zero exit code.`

**Comment by momokoudai** [comment]
同时也找不到 update_checker.vbs
这个。。。。

**Comment by erha19** [comment]
@DamingLake Update to 1.2.5.

**Comment by momokoudai** [comment]
@erha19  
运行weex debug ，weex run XXX
提示找不到  update_checker.vbs 
版本1.2.5
![tim 20180119155811](https://user-images.githubusercontent.com/33850943/35140287-9e1e137c-fd31-11e7-861b-1e5b9fc68b57.jpg)

**Comment by erha19** [comment]
That's a file missing bug ，I will fix it soon also you can find this file on `weexteam/xtoolkit`  the `src/update` floder.

**Comment by erha19** [comment]
@DamingLake now you can upgrade to `v1.2.6`.

**Comment by JaredCen** [comment]
@erha19 This problem is still occurs after i upgrade weex-toolkit to v1.2.6.

**Comment by JunreyCen** [comment]
module.js:540
    throw err;
    ^

Error: Cannot find module '../src/create'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\cenjw\.xtoolkit\node_modules\weexpack\bin\weexpack-create.js:9:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by JunreyCen** [comment]
`module.js:540
    throw err;
    ^

Error: Cannot find module '../src/create'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\cenjw\.xtoolkit\node_modules\weexpack\bin\weexpack-create.js:9:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
`

**Comment by JaredCen** [comment]
```
module.js:540
    throw err;
    ^

Error: Cannot find module '../src/create'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\cenjw\.xtoolkit\node_modules\weexpack\bin\weexpack-create.js:9:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

```

**Comment by erha19** [comment]
change. . ./src. to. ./lib

**Comment by JunreyCen** [comment]
It doesn't work, there is no `src` or `lib` folder

**Comment by JunreyCen** [comment]
Should i downgrade to a low version?

**Comment by JaredCen** [comment]
It doesn't work. It's right that changes `src` to `build`

**Comment by erha19** [comment]
@JunreyCen you can run `weex update weexpack@latest` to upgrade weexpack.

**Comment by melodey** [comment]
@JunreyCen  I also encountered this problem, is it ok now ?

**Comment by melodey** [comment]
@erha19  I have tried, but  it doesn't fix the problem.

**Comment by erha19** [comment]
Give me sometime to find a Windows machine.

**Comment by fumpierrez** [comment]
It happens to me too on OS X

**Comment by erha19** [comment]
#233 @fumpierrez @melodey @JunreyCen Try `weex update weexpack@latest`, latest `weexpack` version is `v1.0.2`.

**Comment by JS-mark** [comment]
![image](https://user-images.githubusercontent.com/31335385/35181171-e364052e-fdf7-11e7-992a-8044a889aedd.png)
重复安装好多遍了，一直都是在报这个错误！

**Comment by JS-mark** [comment]
![image](https://user-images.githubusercontent.com/31335385/35181182-0d667d98-fdf8-11e7-8351-8cc02baf46fd.png)
运行weex命令过后，出现这些，能给个解决方案吗？

**Comment by fumpierrez** [comment]
@Jack-In 
Looks like xtoolkit is not creating ~/.xtoolkit at all (therefore missing  ~/.xtoolkit/config.json)
As a workaround, I created an empty file

`mkdir  ~/.xtoolkit && touch  ~/.xtoolkit/config.json`

And then reinstalled xtoolkit and weex-toolkit successfully 
npm -g uninstall  xtoolkit  and weex-toolkit , then npm -g install them again

**Comment by liushuhui** [comment]
@Jack-In 请问解决了吗？

**Comment by JS-mark** [comment]
@liushuhui 还没有

**Comment by JS-mark** [comment]
![image](https://user-images.githubusercontent.com/31335385/35181171-e364052e-fdf7-11e7-992a-8044a889aedd.png)
请问上边这种情况怎么处理？？？

**Comment by erha19** [comment]
search `how to install node-gyp on Windows`

**Comment by JS-mark** [comment]
![image](https://user-images.githubusercontent.com/31335385/35185218-87cf6f5c-fe3b-11e7-859b-9d8a638faece.png)

出现了新的情况？@erha19

**Comment by erha19** [comment]
@Jack-In same problem,  you need a c++ compiler, you can just install `vs2015` and contain the c++ code compiler.

**Comment by JS-mark** [comment]
![image](https://user-images.githubusercontent.com/31335385/35193711-c6d1d6a8-fee1-11e7-8487-db8d10a2a128.png)
目前只出现这一个，难道还需要其他编译器吗？安装的是vs2017社区版！

**Comment by erha19** [comment]
@Jack-In clear up your `weex-toolkit` directory and try to install on a new shell again, there may be some cache file on your system.

**Comment by y-cares** [comment]
@erha19  自己创建了.xtoolkit 文件，重新安装 weex-toolkit，再安装 weexpack 的时候报这个错，是什么原因？
![image](https://user-images.githubusercontent.com/20083236/35201289-0c8129ec-ff55-11e7-8615-e4ca5ba96512.png)

**Comment by erha19** [comment]
@y-cares try to use it with a admin permission?

**Comment by y-cares** [comment]
@erha19   就是用的管理员权限运行的...

**Comment by y-cares** [comment]
@erha19   第一次是这样的  运行下去  第二次就好了。
话说  ，创建的项目的结构改变了啊   以前老项目的 运行时weex preview src/index.vue 
![image](https://user-images.githubusercontent.com/20083236/35203111-7a700fe8-ff61-11e7-952e-35d18e8a69c3.png)

**Comment by erha19** [comment]
@y-cares run `weex update weex-previewer@latest`, and you can run `weex preview xxx.vue --verbose` show me detail log message.

**Comment by y-cares** [comment]
@erha19   升级之后 直接报错
![image](https://user-images.githubusercontent.com/20083236/35203406-02875e6c-ff63-11e7-88ab-edff0935e164.png)

**Comment by erha19** [comment]
@y-cares run `npm un weex-toolkit@latest -g` and then run `npm i weex-toolkit@latest -g` to roll back to the latest version, I will try to fix this issues.

**Comment by y-cares** [comment]
@erha19   谢啦
 还有一个问题： 之前启动 debug 的时候，要我升级 npm 的版本 >=5.0.0  但是我的npm版本是是 5.6.0 最新的

![tim 20180122110623](https://user-images.githubusercontent.com/20083236/35203669-557d3b86-ff64-11e7-9bcd-4473aa67c371.png)

**Comment by fanzhanxiang** [comment]
![image](https://user-images.githubusercontent.com/32560041/42863012-3f2b99d4-8a94-11e8-8bff-d2389bea2445.png)
weex debug的时候报错，提示找到json文件，这个是什么原因

**Comment by erha19** [comment]
@fanzhanxiang `cd ~/.xtoolkit && npm init`.
